-- tbl_Personeller Tablosunu Olusturma

CREATE TABLE tbl_Personeller
(
Pers_ID int  PRIMARY KEY IDENTITY(1,1) NOT NULL,
Pers_Adi nvarchar(50) NOT NULL,
Pers_Soyadi nvarchar(50) NOT NULL,
Pers_Isim  AS ([Pers_Adi] + [Pers_Soyadi]),
Pers_DTarihi smalldatetime NULL,
Pers_Ise_Giris_Tarihi smalldatetime NULL,
Pers_Isten_Cikis_Tarihi smalldatetime NULL,
Pers_Adresi nvarchar(100) NULL,
Pers_Kenti nvarchar(20) NULL,
Pers_Ili nvarchar(20) NULL,
Pers_Il_Kodu char(2) NULL,
Pers_Tel nvarchar(15) NULL,
Pers_Cep nvarchar(15) NULL,
Pers_Email nvarchar(100) NULL,
Bolum_ID int  NOT NULL,
Pers_Maas money NULL,
Pers_Komisyon_Yuzdesi float NULL,
Cinsiyet_ID int NULL,
Unvan_ID int  NULL,
Pers_SGK_No char(10) NULL,
Pers_TC_No nvarchar(15) NULL,
Pers_Aktif_Mi bit NOT NULL,
Pers_Foto image NULL,
Pers_CV ntext NULL,
Pers_CV_File nvarchar(100) NULL,
Pers_CV_Web nvarchar(2500) NULL,
Kaydeden nvarchar(100) NULL,
Kayit_Tarihi smalldatetime NULL,
)
