CREATE TABLE [dbo].[tbl_Personeller] (
    [Pers_ID]                 INT             IDENTITY (1, 1) NOT NULL,
    [Pers_Adi]                NVARCHAR (50)   NOT NULL,
    [Pers_Soyadi]             NVARCHAR (50)   NOT NULL,
    [Pers_Isim]               AS              (([Pers_Adi] + ' ') + [Pers_Soyadi]),
    [Pers_DTarihi]            SMALLDATETIME   NULL,
    [Pers_Ise_Giris_Tarihi]   SMALLDATETIME   NULL,
    [Pers_Isten_Cikis_Tarihi] SMALLDATETIME   NULL,
    [Pers_Adresi]             NVARCHAR (100)  NULL,
    [Pers_Kenti]              NVARCHAR (20)   NULL,
    [Pers_Ili]                NVARCHAR (20)   NULL,
    [Pers_Il_Kodu]            CHAR (2)        NULL,
    [Pers_Tel]                NVARCHAR (15)   NULL,
    [Pers_Cep]                NVARCHAR (15)   NULL,
    [Pers_Email]              NVARCHAR (100)  NULL,
    [Bolum_ID]                INT             NOT NULL,
    [Pers_Maas]               MONEY           NULL,
    [Pers_Komisyon_Yuzdesi]   FLOAT (53)      NULL,
    [Cinsiyet_ID]             INT             NULL,
    [Unvan_ID]                INT             NULL,
    [Pers_SGK_No]             CHAR (10)       NULL,
    [Pers_TC_No]              NVARCHAR (15)   NULL,
    [Pers_Aktif_Mi]           BIT             NOT NULL,
    [Pers_Foto]               IMAGE           NULL,
    [Pers_CV]                 NTEXT           NULL,
    [Pers_CV_File]            NVARCHAR (100)  NULL,
    [Pers_CV_Web]             NVARCHAR (2500) NULL,
    [Kaydeden]                NVARCHAR (100)  NULL,
    [Kayit_Tarihi]            SMALLDATETIME   NULL,
    CONSTRAINT [PK_tbl_Personeller_Pers_ID] PRIMARY KEY CLUSTERED ([Pers_ID] ASC)
);

