CREATE TABLE [dbo].[tbl_Personeller] (
    [Pers_ID]                 INT             IDENTITY (1, 1) NOT NULL,
    [Pers_Adi]                NVARCHAR (50)   NOT NULL,
    [Pers_Soyadi]             NVARCHAR (50)   NOT NULL,
    [Pers_Isim]               AS              (([Pers_Adi]+' ')+[Pers_Soyadi]),
    [Pers_DTarihi]            SMALLDATETIME   NULL,
    [Pers_Ise_Giris_Tarihi]   SMALLDATETIME   CONSTRAINT [DF_tbl_Personeller_Pers_Ise_Giris_Tarihi] DEFAULT (getdate()) NULL,
    [Pers_Isten_Cikis_Tarihi] SMALLDATETIME   NULL,
    [Pers_Adresi]             NVARCHAR (100)  NULL,
    [Pers_Kenti]              NVARCHAR (20)   NULL,
    [Pers_Ili]                NVARCHAR (20)   NULL,
    [Pers_Il_Kodu]            CHAR (2)        NULL,
    [Pers_Tel]                NVARCHAR (15)   NULL,
    [Pers_Cep]                NVARCHAR (15)   NULL,
    [Pers_Email]              NVARCHAR (100)  NULL,
    [Bolum_ID]                INT             NOT NULL,
    [Pers_Maas]               MONEY           CONSTRAINT [DF_tbl_Personeller_Pers_Maas] DEFAULT ((0)) NULL,
    [Pers_Komisyon_Yuzdesi]   FLOAT (53)      CONSTRAINT [DF_tbl_Personeller_Pers_Komisyon_Yuzdesi] DEFAULT ((0)) NULL,
    [Cinsiyet_ID]             INT             NULL,
    [Unvan_ID]                INT             NULL,
    [Pers_SGK_No]             CHAR (10)       NULL,
    [Pers_TC_No]              NVARCHAR (15)   NULL,
    [Pers_Aktif_Mi]           BIT             CONSTRAINT [DF_tbl_Personeller_Pers_Aktif_Mi] DEFAULT ((1)) NOT NULL,
    [Pers_Foto]               NVARCHAR (10)   NULL,
    [Pers_CV]                 NTEXT           NULL,
    [Pers_CV_File]            NVARCHAR (100)  NULL,
    [Pers_CV_Web]             NVARCHAR (2500) NULL,
    [Kaydeden]                NVARCHAR (100)  CONSTRAINT [DF_tbl_Personeller_Kaydeden] DEFAULT (suser_name()) NULL,
    [Kayit_Tarihi]            SMALLDATETIME   CONSTRAINT [DF_tbl_Personeller_Kayit_Tarihi] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_tbl_Personeller_Pers_ID] PRIMARY KEY CLUSTERED ([Pers_ID] ASC),
    FOREIGN KEY ([Unvan_ID]) REFERENCES [dbo].[tbl_Kategoriler] ([Kategori_ID]),
    FOREIGN KEY ([Unvan_ID]) REFERENCES [dbo].[tbl_Kategoriler] ([Kategori_ID]),
    FOREIGN KEY ([Unvan_ID]) REFERENCES [dbo].[tbl_Kategoriler] ([Kategori_ID]),
    CONSTRAINT [FK_tbl_Personeller_tbl_Kategoriler_Unvan_ID] FOREIGN KEY ([Unvan_ID]) REFERENCES [dbo].[tbl_Kategoriler] ([Kategori_ID])
);

